### ISSUE TITLE
Hello world program fails

### ISSUE THREAD

**Issue by rdebath** [eoli/BrainFuck#1]
This should print "Hello World!" and a newline.

``` bf
>++++++++[-<+++++++++>]<.>[][<-]>+>-[+]++>++>+++[>[->+++<<+++>]<<]>-----.
>->+++..+++.>-.<<+[>[+>+]>>]<--------------.>>.+++.------.--------.>+.>+.
```

Also [this](https://github.com/rdebath/Brainfuck/blob/master/bitwidth.b) should say "Hello World! 255" for your interpreter.

**Comment by eoli** [comment]
Hi rdebath, the bug was fixed.
